version: '3.8'

services:
  # my MongoDB Service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # my Backend Service
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - './backend/.env'
    depends_on:
      - mongodb

  # my Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - './frontend/.env'
    depends_on:
      - backend

volumes:
  mongo-data: